/*
 * ad5941_app.h
 * Public high-level interface to the AD5941 application layer.
 */
#ifndef AD5941_APP_H
#define AD5941_APP_H

#include <stdbool.h>
#include <stdint.h>

enum ad5941_blank_peak_tia_path {
    AD5941_BLANK_PEAK_TIA_LPTIA = 0,
    AD5941_BLANK_PEAK_TIA_HSTIA_INT_160K,
    AD5941_BLANK_PEAK_TIA_HSTIA_EXT_160K,
    AD5941_BLANK_PEAK_TIA_HSTIA_EXT_330K,
    AD5941_BLANK_PEAK_TIA_HSTIA_EXT_680K,
};

enum ad5941_swv_profile {
    AD5941_SWV_PROFILE_5MV_FULL = 0,
    AD5941_SWV_PROFILE_2MV_FULL,
    AD5941_SWV_PROFILE_1MV_SEGMENTED,
};

#define ENABLE_LINEARITY_TEST 1

/**
 * @brief Initialise the AD5941 system.
 *
 * Checks SPI access, performs a hardware reset, and configures clocks and
 * the low-power electrochemical loop.
 *
 * @return 0 on success, or a negative value on failure.
 */
int ad5941_app_init(void);

/**
 * @brief Start the milestone-2 no-load baseline measurement stream.
 */
void ad5941_app_start_measurement(void);

/**
 * @brief Return whether an AD5941 capture/test session is currently active.
 *
 * RTT and BLE command paths use this to avoid starting a new test while the
 * sequencer/FIFO pipeline still belongs to the previous one.
 */
bool ad5941_app_is_measurement_busy(void);

/**
 * @brief Return whether the low-rate nPM1300 battery-current trace is active.
 *
 * SWV data must continue to be sent over BLE, but its large RTT CSV dump is
 * suppressed during this trace so it cannot stall current sampling.
 */
bool nanostat_battery_trace_is_active(void);

/**
 * @brief Clear transient measurement state before starting a new independent test.
 *
 * This stops ADC conversion, disables FIFO watermark IRQs, cancels delayed
 * finish work, clears pending FIFO flags, puts the electrode path into high-Z
 * safe idle, and resets app-side capture bookkeeping. It does not redo the full
 * AD5941 hardware bring-up.
 */
void ad5941_app_soft_reset_for_next_test(void);

/**
 * @brief Start the hardware-sequencer controlled CA test.
 *
 * The sequence applies +100mV with LPDAC, runs ADC conversion for 5 seconds,
 * then stops conversion without MCU timing intervention.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqCA_Test_Start(void);

/**
 * @brief Start the hardware-sequencer controlled CV staircase test.
 *
 * The sequence sweeps LPDAC from about -100mV to +100mV and back with
 * 50ms dwell per step while ADC conversion runs continuously.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqCV_Test_Start(void);

/**
 * @brief Start the hardware-sequencer controlled SWV pulse staircase test.
 *
 * The sequence sweeps the LPDAC base potential from about -100mV to +100mV.
 * At each base step, it applies a +50mV pulse for 25ms followed by a -50mV
 * pulse for 25ms while ADC conversion runs continuously.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_Test_Start(void);

/**
 * @brief Start the sealed SWV-KDM diagnostic test.
 *
 * This keeps the verified long 100ms half-period timing. The ADC runs
 * continuously, then the MCU extracts end-of-pulse Delta_I after capture.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_SinglePoint_Test_Start(void);

/**
 * @brief Start the fast SWV-KDM test.
 *
 * This returns to the 25ms half-period timing and uses a faster SINC2 OSR to
 * check whether the SINC2 settling path caused the attenuated SWV response.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_FastKDM_Test_Start(void);

/**
 * @brief Start the slow-motion SWV single-point test.
 *
 * This keeps RTIA at 512k and stretches each half-pulse to 250ms so the
 * external compensation capacitor can settle.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_SlowMotion_Test_Start(void);

/**
 * @brief Start the low-impedance SWV single-point test.
 *
 * This keeps the 25ms half-pulse timing but forces LPTIA TIAGAIN to 20k and
 * updates current conversion to match the lower RTIA.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_LowImpedance_Test_Start(void);

/**
 * @brief Start the mixed-mode high-speed SWV diagnostic test.
 *
 * The waveform is still generated by LPDAC + Sequencer, but ADC sampling is
 * routed through the HSTIA path with internal 160k RTIA and small CTIA. This
 * diagnostic uses a 20ms half-pulse so a full SWV step aligns to two 50Hz
 * mains cycles.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_MixedModeHSTIA_Test_Start(void);

/**
 * @brief Start the external AIN1 HSTIA 2M SWV comparison test at 150Hz.
 *
 * This uses the PCB DE0-AIN1 external 2M feedback resistor, opens the HSTIA
 * internal RTIA, and matches the LPTIA 150Hz comparison sweep and endpoint
 * extraction settings.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_HSTIAExternalAIN1_Test_Start(void);

/**
 * @brief Start the external AIN1 HSTIA 2M SWV comparison test at 150Hz with Notch enabled.
 *
 * This keeps the HSTIA path identical to App_SeqSWV_HSTIAExternalAIN1_Test_Start()
 * except that the ADC Notch filter is enabled.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_HSTIAExternalAIN1_Notch150Hz_Test_Start(void);

/**
 * @brief Start LPTIA external 2M SWV comparison test at 150Hz.
 *
 * Internal LPTIA RTIA is opened, LPAMP boost is enabled, and the external
 * 2M/220pF feedback path is measured with the same reduced SWV amplitude and
 * endpoint extraction settings used by the HSTIA comparison path.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_LPTIAExternal2M_150Hz_Test_Start(void);

/**
 * @brief Run LPTIA external 2M SWV comparison test five times automatically.
 *
 * This starts the same test as App_SeqSWV_LPTIAExternal2M_150Hz_Test_Start(),
 * repeats it five times, and waits 10 seconds between completed runs.
 *
 * @return 0 on success, <0 on failure.
 */
int App_AutoRepeat_LPTIAExternal2M_150Hz_Test_Start(void);

/**
 * @brief Start LPTIA external 2M SWV diagnostic at 210Hz.
 *
 * Internal LPTIA RTIA is opened, LPAMP boost is enabled, and the external
 * 2M/220pF feedback path is measured with a reduced SWV amplitude while
 * avoiding exact 50Hz phase locking.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_LPTIAExternal2M_200Hz_Test_Start(void);

/**
 * @brief Start boosted LPTIA 512k||2M SWV diagnostic at 150Hz.
 *
 * This keeps the internal 512k RTIA enabled, leaves the external 2M/220pF
 * feedback path in parallel, and enables LPAMP boost.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_LPTIA512KParallel2MBoost150Hz_Test_Start(void);

/**
 * @brief Start LPTIA external 2M SWV diagnostic at 150Hz with boost disabled.
 *
 * This opens the internal LPTIA RTIA and relies on the external 2M/220pF
 * feedback path, but keeps LPAMP in normal power mode.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_LPTIAExternal2M_NoBoost150Hz_Test_Start(void);

/**
 * @brief Start LPTIA external 2M SWV comparison test at 150Hz with Notch enabled.
 *
 * This keeps the LPTIA path identical to App_SeqSWV_LPTIAExternal2M_150Hz_Test_Start()
 * except that the ADC Notch filter is enabled.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_LPTIAExternal2M_Notch150Hz_Test_Start(void);

/**
 * @brief Start a paper-style dual-frequency SWV/KDM dummy-cell test.
 *
 * This uses the LPTIA external 2M/220pF path, runs a 150Hz scan followed by
 * a 10Hz scan over -450mV..0mV, then prints the KDM ratio.
 *
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_KDMPaper_Dummy_Test_Start(void);

/**
 * @brief Start a single-frequency paper-style SWV peak scan for PBS/MB blank tests.
 *
 * This reuses the paper-style SWV window (-450mV..0mV, 35mV pulse, ~5.37mV
 * step) on the LPTIA 512k||external-2M/220pF path, holds the start potential
 * for a quiet time, then runs one user-selected frequency and prints
 * voltage/current CSV rows to RTT.
 *
 * @param frequency_hz SWV frequency in Hz. Valid range is 1..250.
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_BlankPeak_Test_Start(uint32_t frequency_hz);

/**
 * @brief Start the same single-frequency blank/peak scan with extra smoothing columns.
 *
 * RTT/BLE output includes Delta_I_smooth5, Delta_I_smooth7, and a 5-point
 * quadratic Savitzky-Golay smoothed Delta_I value in addition to the existing
 * raw/avg3 data. The scan uses the paper-style -450 mV..0 mV window with
 * approximately 1 mV potential steps, loaded in sequencer segments when needed.
 *
 * @param frequency_hz SWV frequency in Hz. Valid range is 1..250.
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_BlankPeakSmoothing_Test_Start(uint32_t frequency_hz);

/**
 * @brief Start a single-frequency PBS/MB blank/peak scan on the HSTIA 160k path.
 *
 * This keeps the same E_WE-RE window, pulse amplitude, approximately 1 mV
 * potential step, quiet time, endpoint extraction, and smoothing output as
 * App_SeqSWV_BlankPeakSmoothing_Test_Start(), but routes current through the
 * internal HSTIA 160k path to avoid LPTIA saturation when PBS/MB currents are
 * unexpectedly large.
 *
 * @param frequency_hz SWV frequency in Hz. Valid range is 1..250.
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_BlankPeakHSTIA160K_Test_Start(uint32_t frequency_hz);

/**
 * @brief Start a single-frequency PBS/MB blank/peak scan on a selectable TIA path.
 *
 * This is used by RTT and BLE/Web workflows to compare the internal HSTIA
 * 160k resistor with external thin-film HSTIA feedback resistors.
 *
 * @param frequency_hz SWV frequency in Hz. Valid range is 1..250.
 * @param tia_path TIA path/resistor selection.
 * @return 0 on success, <0 on failure.
 */
int App_SeqSWV_BlankPeakSelectableTIA_Test_Start(
    uint32_t frequency_hz,
    enum ad5941_blank_peak_tia_path tia_path);

/**
 * @brief Start a dummy-cell SWV validation scan.
 *
 * This reuses the PBS SWV voltage window and TIA readout path, but reports the
 * run as an ohmic dummy-cell validation instead of an aptasensor peak test.
 */
int App_SeqSWV_DummyCell_Test_Start(enum ad5941_swv_profile profile,
                                    uint32_t frequency_hz,
                                    enum ad5941_blank_peak_tia_path tia_path,
                                    uint32_t dummy_ohms);

/**
 * @brief Start the legacy AIN2-330k dummy-cell SWV comparison path.
 *
 * This is an RTT-only diagnostic used to reproduce the known-good 70 nA
 * dummy-cell result: 120 Hz, 5.37 mV staircase, +/-35 mV SWV pulse,
 * HSTIA external AIN2 330k. It intentionally avoids the new pre-test and
 * in-sequence high-Z guards so it can isolate guard/tail side effects.
 */
int App_SeqSWV_DummyCellLegacyAIN2_Test_Start(uint32_t dummy_ohms);

/**
 * @brief Auto-repeat dummy-cell SWV validation scans.
 */
int App_AutoRepeat_DummySWV_Test_Start(enum ad5941_swv_profile profile,
                                       uint32_t frequency_hz,
                                       enum ad5941_blank_peak_tia_path tia_path,
                                       uint32_t dummy_ohms,
                                       uint8_t repeat_count,
                                       uint32_t interval_ms);

/**
 * @brief Force the AD5941 electrode interface into the safe high-Z idle state.
 */
void ad5941_app_enter_high_z_now(void);

/**
 * @brief Run the high-Z validation scan and hold the final potential.
 *
 * The scan moves from approximately -400 mV to -200 mV and deliberately
 * leaves the electrode path biased at the final potential until a separate
 * high-Z command is received.
 */
int ad5941_app_start_high_z_validation(void);
void ad5941_app_reset_high_z_validation(void);

/**
 * @brief Compare LPTIA external-2M zero-current baseline with offset cal off/on.
 *
 * The test clears ADCOFFSETLPTIA0, captures a 0mV baseline, runs
 * AD5940_LPTIAOffsetCal(), restores the same external 2M path, captures again,
 * prints both statistics, then clears ADCOFFSETLPTIA0 back to zero.
 *
 * @return 0 on success, <0 on failure.
 */
int App_LPTIAOffsetDiagnostic_Test_Start(void);

/**
 * @brief Start an end-to-end LPTIA step response capture.
 *
 * The sequencer holds the LPTIA external 2M/220pF path at 0mV, steps to
 * +100mV, and captures the SINC2 FIFO stream so the MCU can estimate endpoint
 * settling for the current SWV windowing method.
 *
 * @return 0 on success, <0 on failure.
 */
int App_LPTIAStepResponse_Test_Start(void);

/**
 * @brief Start an end-to-end HSTIA external AIN1 step response capture.
 *
 * This mirrors App_LPTIAStepResponse_Test_Start() but routes the ADC through
 * the external AIN1 HSTIA 2M feedback path, currently using the configured
 * HSTIA CTIA value.
 *
 * @return 0 on success, <0 on failure.
 */
int App_HSTIAStepResponse_Test_Start(void);

bool ad5941_app_get_latest_current(int32_t *current_pa, uint32_t *sample_count);

#if ENABLE_LINEARITY_TEST
void ad5941_linearity_test_setup(uint8_t mode);
#endif

/**
 * @brief Put AD5941 interface pins into a safe state before power removal.
 */
void ad5941_app_prepare_shutdown(void);

#endif /* AD5941_APP_H */
